name = "raycasting"

[variables]
cflags = "-Wall -Werror"
libs = "-lraylib -lm"


[task.build]
commands = [
    "gcc $cflags -o $name main.c $libs"
]

[task.run]
depends= [ "build"]
commands = [
    "scp $name soyuz:~/.gitter/",
    "ssh soyuz DISPLAY=:0 /home/pranav/.gitter/$name"
]
