name = "sorts"

[variables]
cflags = "-Wall -Werror"
libs = "-lraylib -lm"

[task.build]
description = "Build the project"
command = "gcc $cflags -o $name main.c $libs"

[task.run]
commands = [
    "scp $name soyuz:~/.gitter/",
    "ssh soyuz DISPLAY=:0 /home/pranav/.gitter/sorts"
]
depends = [
    "build"
]
